namespace TreeCrawler.Domain;

public static class ColorManager
{
    #region Fields

    private static string[] _colors =
    [
        //"aliceblue",
        //"antiquewhite",
        //"antiquewhite1",
        //"antiquewhite2",
        //"antiquewhite3",
        "antiquewhite4",
        "aqua",
        "aquamarine",
        "aquamarine1",
        "aquamarine2",
        "aquamarine3",
        "aquamarine4",
        //"azure",
        //"azure1",
        //"azure2",
        //"azure3",
        //"azure4",
        //"beige",
        //"bisque",
        //"bisque1",
        "bisque2",
        "bisque3",
        "bisque4",
        //"black",
        "blanchedalmond",
        //"blue",
        //"blue1",
        //"blue2",
        //"blue3",
        //"blue4",
        "blueviolet",
        "brown",
        "brown1",
        "brown2",
        "brown3",
        "brown4",
        "burlywood",
        "burlywood1",
        "burlywood2",
        "burlywood3",
        "burlywood4",
        //"cadetblue",
        //"cadetblue1",
        //"cadetblue2",
        //"cadetblue3",
        //"cadetblue4",
        "chartreuse",
        "chartreuse1",
        "chartreuse2",
        "chartreuse3",
        "chartreuse4",
        "chocolate",
        "chocolate1",
        "chocolate2",
        "chocolate3",
        "chocolate4",
        "coral",
        "coral1",
        "coral2",
        "coral3",
        "coral4",
        "cornflowerblue",
        "cornsilk",
        "cornsilk1",
        "cornsilk2",
        "cornsilk3",
        "cornsilk4",
        "crimson",
        "cyan",
        "cyan1",
        "cyan2",
        "cyan3",
        "cyan4",
        "darkblue",
        "darkcyan",
        "darkgoldenrod",
        "darkgoldenrod1",
        "darkgoldenrod2",
        "darkgoldenrod3",
        "darkgoldenrod4",
        "darkgray",
        "darkgreen",
        "darkgrey",
        "darkkhaki",
        "darkmagenta",
        "darkolivegreen",
        "darkolivegreen1",
        "darkolivegreen2",
        "darkolivegreen3",
        "darkolivegreen4",
        "darkorange",
        "darkorange1",
        "darkorange2",
        "darkorange3",
        "darkorange4",
        "darkorchid",
        "darkorchid1",
        "darkorchid2",
        "darkorchid3",
        "darkorchid4",
        "darkred",
        "darksalmon",
        "darkseagreen",
        "darkseagreen1",
        "darkseagreen2",
        "darkseagreen3",
        "darkseagreen4",
        "darkslateblue",
        "darkslategray",
        "darkslategray1",
        "darkslategray2",
        "darkslategray3",
        "darkslategray4",
        "darkslategrey",
        "darkturquoise",
        "darkviolet",
        "deeppink",
        "deeppink1",
        "deeppink2",
        "deeppink3",
        "deeppink4",
        "deepskyblue",
        "deepskyblue1",
        "deepskyblue2",
        "deepskyblue3",
        "deepskyblue4",
        "dimgray",
        "dimgrey",
        "dodgerblue",
        "dodgerblue1",
        "dodgerblue2",
        "dodgerblue3",
        "dodgerblue4",
        "firebrick",
        "firebrick1",
        "firebrick2",
        "firebrick3",
        "firebrick4",
        "floralwhite",
        "forestgreen",
        "fuchsia",
        "gainsboro",
        "ghostwhite",
        "gold",
        "gold1",
        "gold2",
        "gold3",
        "gold4",
        "goldenrod",
        "goldenrod1",
        "goldenrod2",
        "goldenrod3",
        "goldenrod4",
        "gray"
    ];

    #endregion Fields

    #region Methods

    public static string GetColorFromIndex(int idx)
    {
        if (idx > _colors.Length - 1) { idx = 0; }
        return _colors[idx];
    }

    public static int GetIndexFromColor(string color)
    {
        color = color.ToLower();
        for (int i = 0; i < _colors.Length; i++)
        {
            if (color == _colors[i].ToLower()) return i;
        }
        return 0;
    }

    #endregion Methods
}